# WARNING (Autogenerated Code): Editing this file manually is NOT RECOMMENDED! CHANGES MAY BE LOST!
def yourFunction(request, context): 
    from SAAF import Inspector
    import json
    
    inspector = Inspector() 
    inspector.inspectAll()
    
    import subprocess
    json_string = json.dumps(request)
    result = subprocess.run(['bash', 'your_script.sh', json_string], capture_output=True, text=True)
    
    output = result.stdout
    error = result.stderr
    
    try:
        object = json.loads(output)
        for key in object:
            inspector.addAttribute(key, object[key])
    except Exception as e:
        inspector.addAttribute("standard_output", output)
    inspector.addAttribute("error_output", error)

    inspector.inspectAllDeltas()  
    return inspector.finish()
